//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public int Id_StivenKing { get; set; }
        public int Id_GowardLavcraft { get; set; }
        public int Id_JorjOryel { get; set; }
        public string ImagePath { get; set; }
    
        public virtual GowardLavcraft GowardLavcraft { get; set; }
        public virtual JorjOryel JorjOryel { get; set; }
        public virtual StivenKing StivenKing { get; set; }
    }
}
